### PR TITLE
Add iconv and fix tp2 to support encoding

### PR DESCRIPTION
**Pull request by abalabokhin**
Add iconv and fix tp2 to support encoding. Without this Russian tra files that is encoded in CP1251 encoding for classic bg2 cannot encoded in UTF-8 for bg2ee, so all the texts from the after installing it on BG2EE have wrong encoding.

Iconv needs for some other languages as well.

Thanks to Ulpian from arcanecoast.ru.

### CODE REVIEW

**Review by burner1024 — CHANGES_REQUESTED** [review]
1. Proper indentation, please.
2. I don't fully understand how it works. Is it going to re-convert files on each reinstallation of any component?

**Comment by abalabokhin** [comment]
1. I will.
    2. I am not completely sure how it works when you reinstall components (I am not the one, who created the code), but you have very similar code in almost every mode with the support of several languages for EE. As far as I understand all the original tra files are replaced with the converted (to utf-8) version of them once you install any component (and replaced back during uninstalling), but idk what happened when you reinstall components. I can clarify this question if it is important.
    3. These changes are probably from earlier versions of the mode. If there are no lines that needs to be translated in setup.tra file now, you are right, setup should be in noconvert_array and should not be in reload_array (actually there is not harm in converting and reloading it - valid ASCII text is not going to be changed after conversion and reloading, but there is no need to).

**Comment by burner1024** [comment]
2. I took a look at the [code](https://github.com/WeiDUorg/weidu/blob/a4048b11e6904f39ea1f956a36018e5d9a6e8e5c/src/tph/include/handle_charsets.tpa#L279), it seems it's using a marker file to perform the conversion once only.
3. It is up to translators to determine whether `setup.tra` should be translated (although generally it is, otherwise what's the point of having a tra?). The lines contained there are displayed during installation, and because of of that the file is encoded with console encoding (which is `cp866` for Russian in particular).

According to documentation, if `from_utf8` is not set, the whole function does nothing for classic games, and only converts files for EEs. But installation procedure uses the same console on both classic and EEs, so I don't see why `setup.tra` should need conversion on any platform.

**Comment by abalabokhin** [comment]
Usually for most mods lines that are shown in console and lines that are used for items, creatures, etc in tp2 files are mixed in one file. In this case, some lines should be converted and some should not, so the ones that are used to be shown in console usually left in English (ASCII). For mods where lines are divided into separate files (as in your mod) it is probably ok to have "setup" file in native windows console encoding (cp866 for Russian) if a mod is Windows only. Mac and linux consoles are UTF-8, so I would keep all the "setup" lines ASCII only anyway.
Anyway, no conversion (and reloading) should be done for your setup file, I agree here.

**Comment by burner1024** [comment]
Ok, thanks.

**Pull request merged**
