### PR TITLE
Russian translation for the mod by Ulpian and paladin84 from https://arcanecoast.ru/

### PR DESCRIPTION
**Pull request by abalabokhin**
I checked all the changes Russian lines by myself hopefully they are better now.

Proper "ё" character showing depends on the used fonts (as with all the other characters), but all my tests for bg2 vanilla, bgt and bg1 vanilla with the default fonts show that this letter is everywhere by default. I can assume there are Russian fonts without "ё", though...

### CODE REVIEW

**Comment by burner1024** [comment]
Looks better, thanks.
Probably not perfect, but I guess it can be smoothed over with time.

**Comment by abalabokhin** [comment]
I am not sure what happened, but now in the repo some lines for Russian tra file are back to English (and back to Russian for setup.tra file):
1. smarter_familiars.tra: @301, @303, @304, @502
2. setup.tra - should all be in English
3. easy_traps.tra: @114, @115, @120, @123, @127, @131, @132, @133, @134, @136, @140

I believe it is because of the msg2po script. Honestly, I still don't understand the benefits of using this script instead of just simply working with tra files.

**Comment by burner1024** [comment]
Yes, they got reverted because the same translation already existed in PO, just marked as fuzzy, and fuzzy entries are not extracted by default. So in fact PO changes were not matching TRA changes.
I cleared fuzzy flag to allow those strings to be extracted.

The benefit of using the msg2po toolset is simple: it's the only thing that allows to work with tra's in the first place. The source of truth for the translation is the corresponding PO file. Tra's are merely a product of it.

There is no setup.tra in this pull request, so it hasn't been changed at all. I'm not sure why do you want it in English, though.

**Comment by abalabokhin** [comment]
I probably forgot to revert setup.tra file to be ASCII only. I mentioned the reasons in this comment: https://github.com/BGforgeNet/bg2-tweaks-and-tricks/pull/69#issuecomment-1435780620
It is mainly because linux and windows consoles have different encoding, so it is easier to keep all the lines that are shown in console only in ASCII encoding.

Can you do it, please? I can send you the pull request with tra file, but for some reasons `./dir2msgstr.py --auto --overwrite` doesn't change russian.po file after I replaced Russian setup.tra file with the English one.

**Comment by burner1024** [comment]
In general use case console encoding is unknown, be it windows or linux or whatever. So ascii is indeed the safest choice.
However, someone spent time translating that, so I'd rather keep it. Should be easy enough to change encoding based on OS.

**Comment by burner1024** [comment]
OK, might be not so easy, because HANDLE_CHARSETS only supports 1 encoding per language and Russian got 2.
But on the other hand, I reviewed my weidu logs, and there's quite a few mods that use non-ascii characters in component names.
Looks like this is going to need some sort of kludge.

**Comment by abalabokhin** [comment]
Don't assume that if some mods have non-ascii characters they work properly for any OS but windows. Eg. these characters can be easily from the time of bg vanila. Withing the Russian mods translation community  we face old mods with improper showing strings even in windows console all the time.

**Comment by burner1024** [comment]
For further reference, now it is possible to have correct console encodings on all OSes using [handle-charsets](https://github.com/BGforgeNet/handle-charsets).

**Pull request merged**
